# Generated by Django 5.0 on 2024-03-24 04:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plag', '0003_profile_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=255)),
                ('date_uploaded', models.DateField(default=django.utils.timezone.now)),
                ('student', models.PositiveIntegerField()),
                ('lecturer', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plag.upload')),
            ],
        ),
    ]
