# Generated by Django 5.0 on 2024-03-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plag', '0004_upload_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Viewed', 'Viewed')], default='Waiting', max_length=200),
        ),
    ]
