# Generated by Django 5.0 on 2024-03-24 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plag', '0005_upload_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plag.profile'),
        ),
    ]
