# Generated by Django 5.0 on 2024-03-24 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plag', '0006_alter_upload_lecturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='lecturer',
        ),
    ]
