# Generated by Django 5.0 on 2024-03-24 08:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plag', '0007_remove_upload_lecturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='lecturer',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='plag.profile'),
            preserve_default=False,
        ),
    ]
