# Generated by Django 5.0 on 2024-03-24 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plag', '0008_upload_lecturer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='lecturer',
            new_name='lecturer_id',
        ),
    ]
