# Generated by Django 5.0 on 2024-03-24 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plag', '0009_rename_lecturer_upload_lecturer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='lecturer_id',
            new_name='lecturer',
        ),
    ]
